### ISSUE TITLE
Move mysql connection to a seperate file

### ISSUE THREAD

**Issue by arun-wdm** [WisdmLabs/tejas-html-assignment#2]
https://github.com/WisdmLabs/tejas-html-assignment/blob/ec51c38863cca8c505b9c45c88eb7f0e2db1ac1e/UserRegistration.php#L88C9-L98C10

Move mysql connection to a seperate file and reference the file wherever required. This way you can reuse the code.

**Comment by Tejas810** [comment]
Resolved 
https://github.com/WisdmLabs/tejas-html-assignment/blob/PhpAssignment/database-connection.php
