### ISSUE TITLE
Javascript not required here

### ISSUE THREAD

**Issue by arun-wdm** [WisdmLabs/tejas-html-assignment#3]
https://github.com/WisdmLabs/tejas-html-assignment/blob/ec51c38863cca8c505b9c45c88eb7f0e2db1ac1e/index.php#L60

What if this is a security sensitive content?  Anyone could toggle css and view the content.

Hint: Try to do this visibility logic without JS and CSS

**Comment by Tejas810** [comment]
Resolved
https://github.com/WisdmLabs/tejas-html-assignment/blob/PhpAssignment/index.php
