### ISSUE TITLE
Not a good practice to use <br>, use margins and paddings with CSS instead

### ISSUE THREAD

**Issue by arun-wdm** [WisdmLabs/tejas-html-assignment#5]
https://github.com/WisdmLabs/tejas-html-assignment/blob/ec51c38863cca8c505b9c45c88eb7f0e2db1ac1e/index.php#L49

**Comment by Tejas810** [comment]
Resolved 
https://github.com/WisdmLabs/tejas-html-assignment/blob/PhpAssignment/index.php
