### ISSUE TITLE
Filename functions.php does not follow Wordpress coding standards.

### ISSUE THREAD

**Issue by arun-wdm** [WisdmLabs/tejas-html-assignment#6]
https://github.com/WisdmLabs/tejas-html-assignment/blob/f8af3d77ac3384cf041e0752aef53eef06eedf01/woocommerce-checkout-customizer/functions.php#L120

**Comment by arun-wdm** [comment]
Also can you try writing this in a class? OOP approach?

**Comment by Tejas810** [comment]
Resolved 
https://github.com/WisdmLabs/tejas-html-assignment/blob/wordpress_assignment3/woocommerce-checkout-customizer/woocommerce-checkout-customizer.php
