### ISSUE TITLE
Fix function name(prefix), add comments, also change the file name function.php to proper unique file name.

### ISSUE THREAD

**Issue by arun-wdm** [WisdmLabs/tejas-html-assignment#7]
https://github.com/WisdmLabs/tejas-html-assignment/blob/6e7914f5f15f9b0a2eacbb8775c1069228ddfab6/Wordpress%20Assignment2/functions.php#L2

**Comment by Tejas810** [comment]
Resolved
https://github.com/WisdmLabs/tejas-html-assignment/blob/wp_assignment2/Wordpress%20Assignment2/functions.php
